/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import java.time.Clock;
import javax.swing.JOptionPane;
import Fungsi.fungsi;
import java.sql.*;
import java.awt.*;
import javax.swing.JFrame;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author User
 */
public class Login extends javax.swing.JFrame {
    
    public Statement st;
    public ResultSet rs;
    String sql;
    Connection con = koneksi.koneksi.getKoneksi();
    public static String id;
    
//    public static String id2;
    

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        setLocation(
        (screenSize.width - frameSize.width) / 2,
        (screenSize.height - frameSize.height) / 2);
        sadmin.setBackground(new java.awt.Color(26,177,136));


        
    }
    public void login(JTextField user, JTextField pass,String db,String a,String b,String c,String d){
        try {
                String usr = user.getText();
                String pas = pass.getText();
                sql = "SELECT * FROM "+ db +" WHERE "+ a +"='"+ usr +"' AND "+ b +"="+ c +"('"+ pas +"')";
                st = con.createStatement();
                rs = st.executeQuery(sql);
                if(rs.next()){
                    JOptionPane.showMessageDialog(null, "Berhasil Masuk");
                    this.dispose();
                    if(d.equals("admin")){
                        halaman_kepalaperpus ha = new halaman_kepalaperpus();
                        ha.show();
                    }else if(d.equals("petugas")){
                        halaman_petugas ho  = new halaman_petugas();
                        ho.show();
                    }
                    
                }else{
                    JOptionPane.showMessageDialog(null, "Username atau Password SALAH");
                }
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Terjadi Kesalahan");
                user_admin.setText("");
                pass_admin.setText("");
                user_admin.requestFocus();
                petugas_id.setText("");
                pass_petugas.setText("");
                petugas_id.requestFocus();

            }
    }
    
    public static  String getid(){
        return id;
    }
//        public static String getid2(){
//        return id2;
//    }
    
    public Boolean kosong_admin(){
        return (user_admin.getText().equals("") || pass_admin.getText().equals(""));
    }
    
     public Boolean kosong_operator(){
        return (petugas_id.getText().equals("") || pass_petugas.getText().equals(""));
    }
     

    public void exit(){
        admin.setBackground(new java.awt.Color(31,70,112));
        petugas.setBackground(new java.awt.Color(31,70,112));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        close1 = new javax.swing.JButton();
        admin = new javax.swing.JButton();
        petugas = new javax.swing.JButton();
        sadmin = new javax.swing.JPanel();
        spetugas = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        panel_admin = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        user_admin = new javax.swing.JTextField();
        separator_admin1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        pass_admin = new javax.swing.JPasswordField();
        separator_admin2 = new javax.swing.JSeparator();
        masuk_admin = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        panel_petugas = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        petugas_id = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        pass_petugas = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        masuk_petugas = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("EngraversGothic BT", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(28, 42, 57));
        jLabel2.setText("PERPUSTAKAAN");

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(28, 42, 57));
        jLabel10.setText("SMA Negeri 1 Cimaragas");

        jLabel1.setFont(new java.awt.Font("EngraversGothic BT", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addContainerGap(225, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 410, 540));

        jPanel2.setBackground(new java.awt.Color(31, 70, 112));
        jPanel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("LOGIN");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        close1.setBackground(new java.awt.Color(31, 70, 112));
        close1.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        close1.setForeground(new java.awt.Color(255, 255, 255));
        close1.setText("x");
        close1.setToolTipText("Tutup");
        close1.setBorder(null);
        close1.setBorderPainted(false);
        close1.setContentAreaFilled(false);
        close1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close1.setFocusPainted(false);
        close1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close1ActionPerformed(evt);
            }
        });
        jPanel2.add(close1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 32, 29));

        admin.setBackground(new java.awt.Color(31, 70, 112));
        admin.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        admin.setForeground(new java.awt.Color(255, 255, 255));
        admin.setText("Kepala Perpustakaan");
        admin.setBorder(null);
        admin.setBorderPainted(false);
        admin.setContentAreaFilled(false);
        admin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        admin.setOpaque(true);
        admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adminMouseExited(evt);
            }
        });
        admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminActionPerformed(evt);
            }
        });
        jPanel2.add(admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 190, 46));

        petugas.setBackground(new java.awt.Color(31, 70, 112));
        petugas.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        petugas.setForeground(new java.awt.Color(255, 255, 255));
        petugas.setText("Petugas");
        petugas.setBorder(null);
        petugas.setBorderPainted(false);
        petugas.setContentAreaFilled(false);
        petugas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        petugas.setOpaque(true);
        petugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                petugasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                petugasMouseExited(evt);
            }
        });
        petugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petugasActionPerformed(evt);
            }
        });
        jPanel2.add(petugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 150, 46));

        sadmin.setBackground(new java.awt.Color(26, 177, 136));

        javax.swing.GroupLayout sadminLayout = new javax.swing.GroupLayout(sadmin);
        sadmin.setLayout(sadminLayout);
        sadminLayout.setHorizontalGroup(
            sadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        sadminLayout.setVerticalGroup(
            sadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanel2.add(sadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 130, -1, 3));

        spetugas.setBackground(new java.awt.Color(26, 177, 136));

        javax.swing.GroupLayout spetugasLayout = new javax.swing.GroupLayout(spetugas);
        spetugas.setLayout(spetugasLayout);
        spetugasLayout.setHorizontalGroup(
            spetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        spetugasLayout.setVerticalGroup(
            spetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanel2.add(spetugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, -1, 3));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 590, 140));

        jPanel3.setBackground(new java.awt.Color(28, 42, 57));
        jPanel3.setLayout(new java.awt.CardLayout());

        panel_admin.setBackground(new java.awt.Color(31, 70, 112));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Username");

        user_admin.setBackground(new java.awt.Color(31, 70, 112));
        user_admin.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        user_admin.setForeground(new java.awt.Color(255, 255, 255));
        user_admin.setBorder(null);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password");

        pass_admin.setBackground(new java.awt.Color(31, 70, 112));
        pass_admin.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        pass_admin.setForeground(new java.awt.Color(255, 255, 255));
        pass_admin.setBorder(null);
        pass_admin.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        masuk_admin.setBackground(new java.awt.Color(26, 177, 136));
        masuk_admin.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        masuk_admin.setForeground(new java.awt.Color(255, 255, 255));
        masuk_admin.setText("Masuk");
        masuk_admin.setBorder(null);
        masuk_admin.setContentAreaFilled(false);
        masuk_admin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        masuk_admin.setOpaque(true);
        masuk_admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                masuk_adminMouseEntered(evt);
            }
        });
        masuk_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masuk_adminActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Kepala Perpustakaan");

        javax.swing.GroupLayout panel_adminLayout = new javax.swing.GroupLayout(panel_admin);
        panel_admin.setLayout(panel_adminLayout);
        panel_adminLayout.setHorizontalGroup(
            panel_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_adminLayout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(panel_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_adminLayout.createSequentialGroup()
                        .addGroup(panel_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(separator_admin2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(separator_admin1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_adminLayout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(user_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(panel_adminLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(pass_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_adminLayout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(masuk_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_adminLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(167, 167, 167))))
        );
        panel_adminLayout.setVerticalGroup(
            panel_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_adminLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel9)
                .addGap(46, 46, 46)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(user_admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(separator_admin1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(8, 8, 8)
                .addComponent(pass_admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separator_admin2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(masuk_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        jPanel3.add(panel_admin, "card4");

        panel_petugas.setBackground(new java.awt.Color(31, 70, 112));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ID Petugas");

        petugas_id.setBackground(new java.awt.Color(31, 70, 112));
        petugas_id.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        petugas_id.setForeground(new java.awt.Color(255, 255, 255));
        petugas_id.setBorder(null);
        petugas_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petugas_idActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password");

        pass_petugas.setBackground(new java.awt.Color(31, 70, 112));
        pass_petugas.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        pass_petugas.setForeground(new java.awt.Color(255, 255, 255));
        pass_petugas.setBorder(null);
        pass_petugas.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        masuk_petugas.setBackground(new java.awt.Color(26, 177, 136));
        masuk_petugas.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        masuk_petugas.setForeground(new java.awt.Color(255, 255, 255));
        masuk_petugas.setText("Masuk");
        masuk_petugas.setBorder(null);
        masuk_petugas.setContentAreaFilled(false);
        masuk_petugas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        masuk_petugas.setOpaque(true);
        masuk_petugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masuk_petugasActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Petugas");

        javax.swing.GroupLayout panel_petugasLayout = new javax.swing.GroupLayout(panel_petugas);
        panel_petugas.setLayout(panel_petugasLayout);
        panel_petugasLayout.setHorizontalGroup(
            panel_petugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_petugasLayout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(panel_petugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_petugasLayout.createSequentialGroup()
                        .addGroup(panel_petugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(masuk_petugas, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_petugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_petugasLayout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(petugas_id, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(panel_petugasLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(pass_petugas, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_petugasLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(249, 249, 249))))
        );
        panel_petugasLayout.setVerticalGroup(
            panel_petugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_petugasLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel12)
                .addGap(44, 44, 44)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(petugas_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(8, 8, 8)
                .addComponent(pass_petugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(masuk_petugas, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        jPanel3.add(panel_petugas, "card2");

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 590, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void masuk_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masuk_adminActionPerformed
        // TODO add your handling code here:
       if(kosong_admin()){
            JOptionPane.showMessageDialog(null, "Harap Lengkapi Data !","Peringatan", JOptionPane.ERROR_MESSAGE);
       }else{
            login(user_admin,pass_admin,"admin","username","password","","admin");
       }
    }//GEN-LAST:event_masuk_adminActionPerformed

    private void masuk_petugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masuk_petugasActionPerformed
        // TODO add your handling code here:
        if(kosong_operator()){
            JOptionPane.showMessageDialog(null, "Harap Lengkapi Data !","Kesalahan", JOptionPane.ERROR_MESSAGE);
        }else{
            login(petugas_id,pass_petugas,"petugas","id_petugas","password","","petugas");
        }
    }//GEN-LAST:event_masuk_petugasActionPerformed

    private void petugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petugasActionPerformed
        // TODO add your handling code here:
        panel_admin.setVisible(false);
        panel_petugas.setVisible(true);
        sadmin.setBackground(new java.awt.Color(31,70,112));
        spetugas.setBackground(new java.awt.Color(26,177,136));
    }//GEN-LAST:event_petugasActionPerformed

    private void adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminActionPerformed
        // TODO add your handling code here:
        
        panel_petugas.setVisible(false);
        panel_admin.setVisible(true);
        sadmin.setBackground(new java.awt.Color(26,177,136));
        spetugas.setBackground(new java.awt.Color(31,70,112));
    }//GEN-LAST:event_adminActionPerformed

    private void adminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMouseExited
        // TODO add your handling code here:
        exit();
    }//GEN-LAST:event_adminMouseExited

    private void petugasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_petugasMouseExited
        // TODO add your handling code here:
        exit();
    }//GEN-LAST:event_petugasMouseExited

    private void adminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMouseEntered
        // TODO add your handling code here:
        admin.setBackground(new java.awt.Color(197, 211, 226));
//        operator.setBackground(new java.awt.Color(28,42,57));
//        user.setBackground(new java.awt.Color(28,42,57));
    }//GEN-LAST:event_adminMouseEntered

    private void petugasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_petugasMouseEntered
        // TODO add your handling code here:
//        admin.setBackground(new java.awt.Color(28,42,57));
        petugas.setBackground(new java.awt.Color(197, 211, 226));
//        user.setBackground(new java.awt.Color(28,42,57));
    }//GEN-LAST:event_petugasMouseEntered

    private void petugas_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petugas_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_petugas_idActionPerformed

    private void masuk_adminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masuk_adminMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_masuk_adminMouseEntered

    private void close1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close1ActionPerformed
        // TODO add your handling code here:
        fungsi.close();
    }//GEN-LAST:event_close1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admin;
    private javax.swing.JButton close1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JButton masuk_admin;
    private javax.swing.JButton masuk_petugas;
    private javax.swing.JPanel panel_admin;
    private javax.swing.JPanel panel_petugas;
    private javax.swing.JPasswordField pass_admin;
    private javax.swing.JPasswordField pass_petugas;
    private javax.swing.JButton petugas;
    private javax.swing.JTextField petugas_id;
    private javax.swing.JPanel sadmin;
    private javax.swing.JSeparator separator_admin1;
    private javax.swing.JSeparator separator_admin2;
    private javax.swing.JPanel spetugas;
    private javax.swing.JTextField user_admin;
    // End of variables declaration//GEN-END:variables
}
